import { useQuery } from "@tanstack/react-query";
import { ArrowDown, ArrowRight, CalendarDays, ChevronRight, Clock3, MapPin, Phone, Quote, Star } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { getPublicMenu, getPublicRestaurants } from "@/api/public-api";
import { MenuVideoGrid } from "@/features/public-restaurant/components/menu-video/MenuVideoGrid";
import { Reveal } from "@/features/verdant-table/components/Reveal";

const heroImage = "https://lh3.googleusercontent.com/aida-public/AB6AXuBN4pzzLXvJbPivIn4YxM5ZnQLRSGEgm3QTFf18jgdltoRnQE01-YhY0r5ERFBI5NLR2jh6k10qK2LA1vYNgQr5dxdyFbVxWoE03Evvsg0LjvAYoTS3xKmwrN5ky3P30_dJGcATNIMG-AV2a5hdC4fTZ7Pp58-BJ8OHmUrc8Zc1L7byTd40hUk4vgKnQDUys9nz1mykcx3yfjuid9QO9oChSFu1oFbH0KFBJB19K7oK3FgxQexNRVAs";
const testimonials = [
  { quote: "Hər detal düşünülmüş, xidmət isə səssiz bir zəriflikdir.", person: "Aylin M.", role: "Bakı" },
  { quote: "Menyudan atmosferə qədər, axşamımız həqiqətən yadda qaldı.", person: "Kamran R.", role: "Qonaq" },
  { quote: "Müasir mətbəxə və incə xidmətə yeni baxış.", person: "Nigar A.", role: "İcmal" },
];

function scrollTo(id: string) { document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); }

export function CinematicHomePage() {
  const [reviewIndex, setReviewIndex] = useState(0);
  const restaurants = useQuery({ queryKey: ["public-restaurants"], queryFn: getPublicRestaurants });
  const restaurant = restaurants.data?.[0];
  const menu = useQuery({ queryKey: ["public-menu", restaurant?.slug], queryFn: () => getPublicMenu(restaurant!.slug), enabled: Boolean(restaurant?.slug) });
  const dishes = useMemo(() => (menu.data ?? []).flatMap((category) => category.items.filter((item) => item.isAvailable).map((item) => ({ ...item, categoryName: category.name }))).slice(0, 3), [menu.data]);
  const nextReview = () => setReviewIndex((index) => (index + 1) % testimonials.length);
  return <div className="min-h-screen overflow-x-hidden bg-[#fcf9f4] font-[Manrope,ui-sans-serif,system-ui] text-[#1c1c19]">
    <header className="fixed inset-x-0 top-1 z-50 px-4 sm:top-5 sm:px-8"><div className="mx-auto flex h-16 max-w-[1440px] items-center justify-between rounded-full border border-white/20 bg-[#fcf9f4]/70 px-4 shadow-[0_12px_48px_rgba(28,14,19,.14)] backdrop-blur-2xl sm:px-6"><a href="#experience" className="flex items-center gap-3"><img src="/images/hrestaurant-emblem.png" alt="HRestaurant emblemi" className="h-9 w-9 rounded-sm bg-white object-contain p-1" /><span className="font-serif text-lg tracking-[.08em] text-[#32091a] sm:text-xl">HRESTAURANT</span></a><nav aria-label="Əsas naviqasiya" className="hidden items-center gap-8 lg:flex">{[["TƏCRÜBƏ","experience"],["MENYU","menu"],["FİLİALLAR","locations"],["REZERVASİYA","reservation"]].map(([label, id]) => <button key={id} type="button" onClick={() => scrollTo(id)} className="text-[10px] font-bold tracking-[.18em] text-[#514347] transition hover:text-[#32091a]">{label}</button>)}</nav><div className="flex items-center gap-2"><button type="button" onClick={() => scrollTo("reservation")} className="hidden rounded-full bg-[#32091a] px-5 py-3 text-[10px] font-bold tracking-[.12em] text-white transition hover:bg-[#4b1e2f] sm:block">MASA REZERV ET</button><Link to="/reservation/track" aria-label="Rezervasiyanı yoxla" className="grid h-9 w-9 place-items-center rounded-full bg-[#32091a] text-white"><CalendarDays className="h-4 w-4" /></Link></div></div></header>
    <main>
      <section id="experience" className="relative flex min-h-[780px] items-center justify-center overflow-hidden px-5 pt-24 text-center text-white sm:min-h-screen"><div className="absolute inset-0 -z-20 bg-cover bg-center motion-safe:animate-[cinema-drift_18s_ease-in-out_infinite_alternate]" style={{ backgroundImage: `url(${heroImage})` }} /><div className="absolute inset-0 -z-10 bg-[linear-gradient(180deg,rgba(13,10,11,.72),rgba(32,13,20,.36),rgba(13,10,11,.84))]" /><div className="pointer-events-none absolute -left-40 top-1/3 h-96 w-96 rounded-full bg-[#e3c281]/20 blur-[120px]" /><Reveal className="max-w-4xl pt-16"><p className="text-[10px] font-bold tracking-[.28em] text-[#e3c281]">HRESTAURANT · FINE DINING</p><h1 className="mt-7 font-serif text-[clamp(3.5rem,7vw,6.6rem)] leading-[.86] tracking-[-.035em]">Fine dining təcrübəsi<br /><em className="font-normal text-[#e3c281]">hər zamankından fərqli.</em></h1><p className="mx-auto mt-7 max-w-2xl text-sm leading-7 text-white/78 sm:text-base">Dəbdəbəli atmosfer, ustalıqla hazırlanmış yeməklər və unudulmaz anlar — zövqü seçən qonaqlar üçün.</p><div className="mt-9 flex flex-wrap justify-center gap-3"><button type="button" onClick={() => scrollTo("reservation")} className="rounded-full bg-[#e3c281] px-7 py-4 text-[11px] font-bold tracking-[.15em] text-[#261a00] transition hover:-translate-y-0.5 hover:bg-[#ffdf9f]">MASA REZERV ET</button><button type="button" onClick={() => scrollTo("menu")} className="rounded-full border border-white/35 bg-white/5 px-7 py-4 text-[11px] font-bold tracking-[.15em] text-white backdrop-blur transition hover:bg-white/15">MENYUYA BAX</button></div></Reveal><button type="button" onClick={() => scrollTo("menu")} aria-label="Menyu bölməsinə keç" className="absolute bottom-9 left-1/2 grid -translate-x-1/2 place-items-center text-[#e3c281]"><span className="mb-2 text-[9px] tracking-[.25em] text-white/70">AŞAĞI</span><ArrowDown className="h-5 w-5 animate-bounce" /></button></section>
      <section id="menu" className="bg-[#fcf9f4] px-5 py-24 sm:px-8 lg:px-20 lg:py-32"><div className="mx-auto max-w-[1440px]"><Reveal><div className="flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div><p className="text-[10px] font-bold tracking-[.24em] text-[#ae9154]">İMZA YARADILIŞLAR</p><h2 className="mt-4 max-w-2xl font-serif text-4xl leading-tight sm:text-5xl">Mükəmməl dəqiqliklə hazırlanmış kulinariya şah əsərləri.</h2></div>{restaurant && <Link to={`/restaurants/${restaurant.slug}/menu`} className="inline-flex items-center gap-2 text-[11px] font-bold tracking-[.13em] text-[#32091a] hover:text-[#844e60]">BÜTÜN MENYU <ArrowRight className="h-4 w-4" /></Link>}</div></Reveal>{menu.isLoading || restaurants.isLoading ? <div className="mt-12 grid h-72 place-items-center bg-[#f0ede9] text-[#514347]">Menyu yüklənir…</div> : dishes.length > 0 && restaurant ? <MenuVideoGrid items={dishes} restaurantSlug={restaurant.slug} /> : <div className="mt-12 rounded-xl border border-[#d5c2c6] bg-[#f6f3ee] p-12 text-center"><h3 className="font-serif text-3xl">Menyu tezliklə təqdim olunacaq</h3><p className="mt-3 text-[#514347]">Məhsullar əlavə edildikdə burada canlı görünəcək.</p></div>}</div></section>
      <section className="bg-[#1c1c19] px-5 py-24 text-[#f3f0eb] sm:px-8 lg:px-20 lg:py-32"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[1.1fr_.9fr]"><Reveal><div className="min-h-[440px] bg-cover bg-center" style={{ backgroundImage: `linear-gradient(0deg,rgba(28,28,25,.16),rgba(28,28,25,.16)),url(${heroImage})` }} /></Reveal><Reveal delay={100} className="self-center"><p className="text-[10px] font-bold tracking-[.24em] text-[#e3c281]">HRESTAURANT HEKAYƏSİ</p><h2 className="mt-5 font-serif text-5xl leading-[.95]">Bir axşamdan daha çoxu.</h2><p className="mt-6 max-w-xl leading-7 text-white/65">HRestaurant-da mətbəx sadəcə servis deyil. Bu, hər teksturanın, işığın və söhbətin incəliklə qurulduğu duyğusal bir səhnədir.</p><div className="mt-10 grid grid-cols-2 gap-6 sm:grid-cols-4">{[["12+","İllik təcrübə"],["18","Peşəkar aşpaz"],["64","İmza yemək"],["24K","Məmnun qonaq"]].map(([value,label]) => <div key={label} className="border-l border-[#e3c281]/40 pl-4"><strong className="font-serif text-3xl text-[#e3c281]">{value}</strong><span className="mt-2 block text-xs text-white/55">{label}</span></div>)}</div></Reveal></div></section>
      <section id="locations" className="bg-[#f6f3ee] px-5 py-24 sm:px-8 lg:px-20 lg:py-32"><div className="mx-auto max-w-[1440px]"><Reveal><p className="text-[10px] font-bold tracking-[.24em] text-[#ae9154]">MƏKANLARIMIZ</p><h2 className="mt-4 font-serif text-5xl">Memarlıq sığınacaqları.</h2></Reveal><div className="mt-12 grid gap-6 lg:grid-cols-3">{(restaurants.data ?? []).map((branch, index) => <Reveal key={branch.id} delay={index * 80}><article className="overflow-hidden border border-[#d5c2c6]/60 bg-white shadow-[0_24px_70px_rgba(49,27,34,.06)]"><div className="aspect-[16/10] bg-[#e5e2dd]">{branch.coverImageUrl ? <img src={branch.coverImageUrl} alt={`${branch.name} interyeri`} className="h-full w-full object-cover" /> : <div className="h-full bg-[linear-gradient(135deg,#4b1e2f,#1c1c19)]" />}</div><div className="p-6"><p className="text-[10px] font-bold tracking-[.16em] text-[#ae9154]">0{index + 1} · {branch.isOpenNow ? "AÇIQ" : "BAĞLI"}</p><h3 className="mt-3 font-serif text-3xl">{branch.name}</h3><p className="mt-4 flex gap-2 text-sm leading-6 text-[#514347]"><MapPin className="mt-0.5 h-4 w-4 shrink-0 text-[#844e60]" />{branch.address}</p><div className="mt-6 flex gap-3"><Link to={`/restaurants/${branch.slug}`} className="inline-flex items-center gap-1 bg-[#32091a] px-4 py-3 text-[10px] font-bold tracking-[.12em] text-white">KƏŞF ET <ChevronRight className="h-3 w-3" /></Link><Link to={`/restaurants/${branch.slug}/reservation`} className="border border-[#32091a]/25 px-4 py-3 text-[10px] font-bold tracking-[.12em] text-[#32091a]">REZERV ET</Link></div></div></article></Reveal>)}</div></div></section>
      <section className="bg-[#4b1e2f] px-5 py-24 text-white sm:px-8 lg:px-20"><Reveal className="mx-auto max-w-3xl text-center"><Quote className="mx-auto h-7 w-7 text-[#e3c281]" /><div className="mt-7 flex justify-center gap-1 text-[#e3c281]">{Array.from({ length: 5 }, (_, index) => <Star key={index} className="h-4 w-4 fill-current" />)}</div><p className="mt-7 font-serif text-3xl leading-relaxed sm:text-4xl">“{testimonials[reviewIndex].quote}”</p><p className="mt-6 text-[11px] font-bold tracking-[.14em] text-white/65">{testimonials[reviewIndex].person} · {testimonials[reviewIndex].role}</p><button type="button" onClick={nextReview} className="mt-8 border-b border-[#e3c281] pb-1 text-[10px] font-bold tracking-[.2em] text-[#e3c281]">NÖVBƏTİ RƏY</button></Reveal></section>
      <section id="reservation" className="relative overflow-hidden bg-[#1c1c19] px-5 py-28 text-center text-white sm:px-8 lg:py-36"><div className="absolute inset-0 -z-10 bg-cover bg-center opacity-30" style={{ backgroundImage: `url(${heroImage})` }} /><Reveal><p className="text-[10px] font-bold tracking-[.24em] text-[#e3c281]">AXŞAMINIZI PLANLAYIN</p><h2 className="mt-5 font-serif text-5xl leading-none sm:text-7xl">Mükəmməl axşamınızı<br /><em className="font-normal text-[#e3c281]">rezerv edin.</em></h2><p className="mx-auto mt-6 max-w-xl text-white/70">HRestaurant-da bütün diqqət masanızdakı anlara yönəlir.</p><div className="mt-9 flex flex-wrap justify-center gap-3">{restaurant && <Link to={`/restaurants/${restaurant.slug}/reservation`} className="rounded-full bg-[#e3c281] px-7 py-4 text-[11px] font-bold tracking-[.15em] text-[#261a00]">İNDİ REZERV ET</Link>}<a href={`tel:${restaurant?.phone ?? ""}`} className="inline-flex items-center gap-2 rounded-full border border-white/35 px-7 py-4 text-[11px] font-bold tracking-[.15em] text-white"><Phone className="h-4 w-4" /> RESTORANA ZƏNG ET</a></div></Reveal></section>
    </main>
    <footer className="bg-[#f0ede9] px-5 py-14 text-[#514347] sm:px-8 lg:px-20"><div className="mx-auto flex max-w-[1440px] flex-col gap-10 border-b border-[#d5c2c6] pb-10 md:flex-row md:justify-between"><div><img src="/images/hrestaurant-emblem.png" alt="HRestaurant" className="h-12 w-12 bg-white object-contain p-1" /><p className="mt-4 font-serif text-2xl text-[#32091a]">HRestaurant</p><p className="mt-2 max-w-xs text-sm">Kulinariya dəqiqliyi və qlobal duyğusal lüks.</p></div><div><p className="text-[10px] font-bold tracking-[.2em]">ƏLAQƏ</p><p className="mt-4 text-sm">{restaurant?.address ?? "HRestaurant"}</p><a href={`tel:${restaurant?.phone ?? ""}`} className="mt-2 block text-sm hover:text-[#32091a]">{restaurant?.phone ?? ""}</a><p className="mt-4 flex items-center gap-2 text-sm"><Clock3 className="h-4 w-4" /> Hər gün sizi gözləyirik</p></div></div><p className="mx-auto max-w-[1440px] pt-6 text-[10px] tracking-[.16em]">© {new Date().getFullYear()} HRESTAURANT GROUP. BÜTÜN HÜQUQLAR QORUNUR.</p></footer>
  </div>;
}
