import { Clock3, ExternalLink, MapPin, Navigation, Phone } from "lucide-react";
import { Link } from "react-router-dom";
import type { PublicBranch } from "@/types/public";

const safeHttpUrl = (value: string | null) => { if (!value) return null; try { const url = new URL(value); return url.protocol === "https:" || url.protocol === "http:" ? url.href : null; } catch { return null; } };
export const branchImage = (branch: PublicBranch, fallback?: string | null) => branch.frontImageUrl || branch.coverImageUrl || fallback || null;

export function BranchWorkingHours({ branch }: { branch: PublicBranch }) { return <div className="space-y-2">{branch.workingHours.map((hour) => <div key={hour.dayOfWeek} className="flex justify-between gap-4 text-sm"><span>{hour.dayName}</span><span>{hour.isClosed ? "Bağlı" : `${hour.opensAt?.slice(0, 5)}–${hour.closesAt?.slice(0, 5)}`}</span></div>)}</div>; }

export function BranchDirectionsButton({ branch }: { branch: PublicBranch }) { const href = branch.latitude != null && branch.longitude != null ? `https://www.google.com/maps/dir/?api=1&destination=${branch.latitude},${branch.longitude}` : safeHttpUrl(branch.googleMapsUrl); return href ? <a href={href} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-full border border-[#d7a64a] px-5 font-bold text-[#d7a64a]"><Navigation className="h-4 w-4" />Yol tarifi al</a> : null; }

export function BranchReservationButton({ branch, restaurantSlug }: { branch: PublicBranch; restaurantSlug: string }) { return <Link to={`/restaurants/${restaurantSlug}/reservation?branchId=${branch.id}`} className="inline-flex min-h-11 items-center justify-center rounded-full bg-[#c55232] px-5 font-bold text-white">Masa rezerv et</Link>; }

export function BranchMap({ branch }: { branch: PublicBranch }) { if (branch.latitude == null || branch.longitude == null) return branch.googleMapsUrl ? <div className="grid aspect-video place-items-center rounded-3xl bg-white/5"><BranchDirectionsButton branch={branch} /></div> : <div className="rounded-3xl border border-white/10 p-6"><MapPin className="mb-3 h-6 w-6" /><p>{branch.address}</p><p className="mt-2 text-sm text-[#baa999]">Bu filial üçün xəritə koordinatları daxil edilməyib.</p></div>; const src = `https://www.openstreetmap.org/export/embed.html?bbox=${branch.longitude - .01}%2C${branch.latitude - .01}%2C${branch.longitude + .01}%2C${branch.latitude + .01}&layer=mapnik&marker=${branch.latitude}%2C${branch.longitude}`; return <iframe title={`${branch.name} xəritəsi`} src={src} loading="lazy" referrerPolicy="no-referrer-when-downgrade" className="aspect-video w-full rounded-3xl border-0" />; }

export function BranchFrontView({ branch, fallback }: { branch: PublicBranch; fallback?: string | null }) { const image = branchImage(branch, fallback); return image ? <img src={image} loading="lazy" alt={`${branch.name} filialının ön görünüşü`} className="aspect-[16/9] h-full w-full rounded-3xl object-cover" /> : <div className="grid aspect-video place-items-center rounded-3xl bg-white/5"><MapPin className="h-12 w-12 text-[#d7a64a]" /><span className="sr-only">Filial şəkli yoxdur</span></div>; }
export function BranchGallery({ branch, fallback }: { branch: PublicBranch; fallback?: string | null }) { const images = [...new Set([branch.frontImageUrl, branch.coverImageUrl, fallback].filter(Boolean))] as string[]; return <div className="grid gap-3 sm:grid-cols-2">{images.map((src, index) => <img key={src} src={src} loading="lazy" alt={`${branch.name} görünüşü ${index + 1}`} className="aspect-video w-full rounded-2xl object-cover" />)}</div>; }
export function BranchInfoPanel({ branch }: { branch: PublicBranch }) { const tour = safeHttpUrl(branch.virtualTourUrl); return <aside className="rounded-3xl border border-white/10 bg-white/5 p-6"><span className={`rounded-full px-3 py-1 text-xs font-bold ${branch.isOpenNow ? "bg-emerald-400/15 text-emerald-300" : "bg-red-400/15 text-red-300"}`}>{branch.isOpenNow ? "İndi açıqdır" : "İndi bağlıdır"}</span><h1 className="mt-4 font-serif text-4xl">{branch.name}</h1><p className="mt-3 text-[#d8c9b6]">{branch.shortDescription}</p><p className="mt-5 flex gap-2"><MapPin className="h-5 w-5 shrink-0" />{branch.address}</p>{branch.phone && <a href={`tel:${branch.phone}`} className="mt-3 flex gap-2"><Phone className="h-5 w-5" />{branch.phone}</a>}{branch.landmark && <p className="mt-3 text-sm">Orientir: {branch.landmark}</p>}{branch.parkingInfo && <p className="mt-3 text-sm">Parkinq: {branch.parkingInfo}</p>}<div className="mt-6 border-t border-white/10 pt-5"><h2 className="mb-3 flex items-center gap-2 font-bold"><Clock3 className="h-4 w-4" />İş saatları</h2><BranchWorkingHours branch={branch} /></div>{tour && <a href={tour} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-[#d7a64a]">Virtual tur <ExternalLink className="h-4 w-4" /></a>}</aside>; }

export function BranchCard({ branch, restaurantSlug, fallback }: { branch: PublicBranch; restaurantSlug: string; fallback?: string | null }) { return <article className="overflow-hidden rounded-3xl border border-white/10 bg-white/5"><BranchFrontView branch={branch} fallback={fallback} /><div className="p-6"><div className="flex items-start justify-between gap-3"><h2 className="font-serif text-3xl">{branch.name}</h2><span className={branch.isOpenNow ? "text-emerald-300" : "text-red-300"}>{branch.isOpenNow ? "Açıq" : "Bağlı"}</span></div><p className="mt-3 text-[#d8c9b6]">{branch.address}</p>{branch.phone && <p className="mt-2">{branch.phone}</p>}<div className="mt-5 flex flex-wrap gap-3"><BranchDirectionsButton branch={branch} /><Link to={`/restaurants/${restaurantSlug}/branches/${branch.id}`} className="inline-flex min-h-11 items-center rounded-full border border-white/20 px-5 font-bold">Ətraflı bax</Link><BranchReservationButton branch={branch} restaurantSlug={restaurantSlug} /></div></div></article>; }
export function BranchList({ branches, restaurantSlug, fallback }: { branches: PublicBranch[]; restaurantSlug: string; fallback?: string | null }) { return <div className="grid gap-6 md:grid-cols-2">{branches.map((branch) => <BranchCard key={branch.id} branch={branch} restaurantSlug={restaurantSlug} fallback={fallback} />)}</div>; }
