import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Edit3, Plus, Power, RefreshCw, Search, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { branchApi, branchKeys } from "@/api/branchApi";
import type { BranchDto } from "@/api/contracts";
import { useAuthStore } from "@/features/auth/store/auth-store";
import { Badge } from "@/shared/components/Badge";
import { Button } from "@/shared/components/Button";
import { FormField } from "@/shared/components/FormField";
import { Modal } from "@/shared/components/Modal";
import { PageHeader } from "@/shared/components/PageHeader";
import { EmptyState, ErrorState, LoadingState } from "@/shared/components/StatePanel";
import { getErrorMessage } from "@/shared/lib/utils";

const optionalUrl = z.string().trim().url("Düzgün URL daxil edin").or(z.literal(""));
const schema = z.object({ name: z.string().trim().min(2).max(100), slug: z.string().trim().regex(/^[A-Za-z0-9-]*$/), address: z.string().trim().min(3).max(250), phone: z.string().max(20), email: z.string().email().or(z.literal("")), latitude: z.number().min(-90).max(90).nullable(), longitude: z.number().min(-180).max(180).nullable(), frontImageUrl: optionalUrl, coverImageUrl: optionalUrl, shortDescription: z.string().max(500), googleMapsUrl: optionalUrl, virtualTourUrl: optionalUrl, parkingInfo: z.string().max(500), landmark: z.string().max(250), isPubliclyVisible: z.boolean(), timeZoneId: z.string().min(1) });
type Values = z.infer<typeof schema>;
const defaults: Values = { name: "", slug: "", address: "", phone: "", email: "", latitude: null, longitude: null, frontImageUrl: "", coverImageUrl: "", shortDescription: "", googleMapsUrl: "", virtualTourUrl: "", parkingInfo: "", landmark: "", isPubliclyVisible: true, timeZoneId: "Asia/Baku" };
const clean = (values: Values) => ({ ...values, phone: values.phone || undefined, email: values.email || undefined, frontImageUrl: values.frontImageUrl || undefined, coverImageUrl: values.coverImageUrl || undefined, shortDescription: values.shortDescription || undefined, googleMapsUrl: values.googleMapsUrl || undefined, virtualTourUrl: values.virtualTourUrl || undefined, parkingInfo: values.parkingInfo || undefined, landmark: values.landmark || undefined });

export function BranchPage() {
  const restaurantId = useAuthStore((state) => state.user?.restaurantId ?? "");
  const [search, setSearch] = useState(""); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<BranchDto | null>(null);
  const queryClient = useQueryClient();
  const query = useQuery({ queryKey: [...branchKeys.all, search], queryFn: ({ signal }) => branchApi.list({ pageSize: 100, search: search || undefined, signal }) });
  const { register, handleSubmit, reset, formState: { errors } } = useForm<Values>({ resolver: zodResolver(schema), defaultValues: defaults });
  useEffect(() => { if (open) reset(editing ? { name: editing.name, slug: editing.slug, address: editing.address, phone: editing.phone ?? "", email: editing.email ?? "", latitude: editing.latitude, longitude: editing.longitude, frontImageUrl: editing.frontImageUrl ?? "", coverImageUrl: editing.coverImageUrl ?? "", shortDescription: editing.shortDescription ?? "", googleMapsUrl: editing.googleMapsUrl ?? "", virtualTourUrl: editing.virtualTourUrl ?? "", parkingInfo: editing.parkingInfo ?? "", landmark: editing.landmark ?? "", isPubliclyVisible: editing.isPubliclyVisible, timeZoneId: editing.timeZoneId } : defaults); }, [editing, open, reset]);
  const save = useMutation({ mutationFn: (values: Values) => editing ? branchApi.update(editing.id, clean(values)) : branchApi.create({ ...clean(values), restaurantId }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: branchKeys.all }); setOpen(false); setEditing(null); } });
  const action = useMutation({ mutationFn: ({ id, kind, active }: { id: string; kind: "delete" | "active"; active?: boolean }) => kind === "delete" ? branchApi.remove(id) : branchApi.setActive(id, Boolean(active)), onSuccess: () => queryClient.invalidateQueries({ queryKey: branchKeys.all }) });
  return <div className="page-enter space-y-6"><PageHeader eyebrow="Struktur" title="Filiallar" description="Filial məlumatları, media, xəritə və public görünürlük." actions={<Button onClick={() => { setEditing(null); setOpen(true); }}><Plus className="h-4 w-4" />Yeni filial</Button>} />
    <div className="card flex gap-3 p-4"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2" /><input value={search} onChange={(event) => setSearch(event.target.value)} className="h-11 w-full rounded-xl border pl-10 pr-3" placeholder="Filial axtar..." /></label><Button variant="secondary" loading={query.isFetching} onClick={() => query.refetch()}><RefreshCw className="h-4 w-4" />Yenilə</Button></div>
    {query.isLoading ? <LoadingState label="Filiallar yüklənir" /> : query.isError ? <ErrorState message={getErrorMessage(query.error)} onRetry={() => query.refetch()} /> : !query.data?.data?.length ? <EmptyState title="Filial yoxdur" /> : <div className="table-shell overflow-x-auto"><table className="data-table min-w-[800px]"><thead><tr><th>Filial</th><th>Ünvan</th><th>Əlaqə</th><th>Public</th><th>Status</th><th>Əməliyyat</th></tr></thead><tbody>{query.data.data.map((branch) => <tr key={branch.id}><td><p className="font-bold">{branch.name}</p><p className="text-xs">/{branch.slug}</p></td><td>{branch.address}</td><td>{branch.phone || branch.email || "—"}</td><td>{branch.isPubliclyVisible ? "Görünür" : "Gizli"}</td><td><Badge tone={branch.isActive ? "success" : "danger"}>{branch.isActive ? "Aktiv" : "Deaktiv"}</Badge></td><td><div className="flex gap-1"><button type="button" aria-label="Redaktə et" className="rounded-lg p-2" onClick={() => { setEditing(branch); setOpen(true); }}><Edit3 className="h-4 w-4" /></button><button type="button" aria-label="Statusu dəyiş" className="rounded-lg p-2" onClick={() => action.mutate({ id: branch.id, kind: "active", active: !branch.isActive })}><Power className="h-4 w-4" /></button><button type="button" aria-label="Sil" className="rounded-lg p-2 text-red-600" onClick={() => { if (window.confirm(`${branch.name} filialı silinsin?`)) action.mutate({ id: branch.id, kind: "delete" }); }}><Trash2 className="h-4 w-4" /></button></div></td></tr>)}</tbody></table></div>}
    <Modal open={open} onClose={() => setOpen(false)} title={editing ? "Filialı redaktə et" : "Yeni filial"}><form className="space-y-4" onSubmit={handleSubmit((values) => save.mutate(values))}><div className="grid gap-4 sm:grid-cols-2"><FormField label="Ad" error={errors.name?.message} {...register("name")} /><FormField label="Slug" error={errors.slug?.message} {...register("slug")} /></div><FormField label="Ünvan" error={errors.address?.message} {...register("address")} /><div className="grid gap-4 sm:grid-cols-2"><FormField label="Telefon" {...register("phone")} /><FormField label="Email" type="email" error={errors.email?.message} {...register("email")} /></div><div className="grid gap-4 sm:grid-cols-2"><FormField label="Latitude" type="number" step="0.000001" error={errors.latitude?.message} {...register("latitude", { setValueAs: (value) => value === "" ? null : Number(value) })} /><FormField label="Longitude" type="number" step="0.000001" error={errors.longitude?.message} {...register("longitude", { setValueAs: (value) => value === "" ? null : Number(value) })} /></div><FormField label="Qısa təsvir" error={errors.shortDescription?.message} {...register("shortDescription")} /><div className="grid gap-4 sm:grid-cols-2"><FormField label="Ön görünüş URL-i" error={errors.frontImageUrl?.message} {...register("frontImageUrl")} /><FormField label="Cover URL-i" error={errors.coverImageUrl?.message} {...register("coverImageUrl")} /><FormField label="Google Maps URL-i" error={errors.googleMapsUrl?.message} {...register("googleMapsUrl")} /><FormField label="Virtual tur URL-i" error={errors.virtualTourUrl?.message} {...register("virtualTourUrl")} /></div><div className="grid gap-4 sm:grid-cols-2"><FormField label="Parkinq məlumatı" {...register("parkingInfo")} /><FormField label="Orientir" {...register("landmark")} /></div><label className="flex items-center gap-2"><input type="checkbox" {...register("isPubliclyVisible")} />Public saytda göstər</label><FormField label="Saat qurşağı" {...register("timeZoneId")} />{save.isError && <p className="text-red-700">{getErrorMessage(save.error)}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => setOpen(false)}>Ləğv et</Button><Button type="submit" loading={save.isPending}>Yadda saxla</Button></div></form></Modal>
  </div>;
}
