import { useQuery } from "@tanstack/react-query";
import { ArrowRight, Search, Sparkles, UtensilsCrossed } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getPublicApiError, getPublicMenu, getPublicRestaurant } from "@/api/public-api";
import { MenuVideoGrid } from "@/features/public-restaurant/components/menu-video/MenuVideoGrid";

export function PublicMenuPage() {
  const { restaurantSlug = "" } = useParams();
  const [search, setSearch] = useState("");
  const [categoryId, setCategoryId] = useState("");
  const [popular, setPopular] = useState(false);
  const restaurant = useQuery({ queryKey: ["public-restaurant", restaurantSlug], queryFn: () => getPublicRestaurant(restaurantSlug), enabled: Boolean(restaurantSlug) });
  const menu = useQuery({ queryKey: ["public-menu", restaurantSlug], queryFn: () => getPublicMenu(restaurantSlug), enabled: Boolean(restaurantSlug) });
  useEffect(() => { if (restaurant.data) document.title = `${restaurant.data.name} · Menyu`; }, [restaurant.data]);
  const items = useMemo(() => (menu.data ?? []).flatMap((category) => category.items.map((item) => ({ ...item, categoryName: category.name }))).filter((item) => (!categoryId || item.categoryId === categoryId) && (!search || `${item.name} ${item.description} ${item.ingredients.join(" ")}`.toLowerCase().includes(search.toLowerCase())) && (!popular || item.isPopular) && item.isAvailable), [categoryId, menu.data, popular, search]);
  if (menu.isLoading || restaurant.isLoading) return <div className="min-h-screen bg-[#fcfbf6] px-5 py-20"><div className="mx-auto max-w-7xl animate-pulse"><div className="h-14 max-w-lg rounded-2xl bg-[#d9ead6]" /><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><div className="h-80 rounded-3xl bg-[#e8f2e4]" /><div className="h-80 rounded-3xl bg-[#e8f2e4]" /></div></div></div>;
  if (menu.isError || restaurant.isError) return <div className="grid min-h-[60vh] place-items-center bg-[#fcfbf6] px-5 text-center"><div><h1 className="font-serif text-4xl text-[#173d2b]">Menyu yüklənmədi</h1><p className="mt-3 text-[#5d6b60]">{getPublicApiError(menu.error ?? restaurant.error).message}</p><button type="button" className="mt-6 rounded-full bg-[#173d2b] px-6 py-3 font-bold text-white" onClick={() => { void menu.refetch(); void restaurant.refetch(); }}>Yenidən cəhd et</button></div></div>;
  return <section className="min-h-screen overflow-hidden bg-[#fcfbf6] px-5 py-12 text-[#173d2b] sm:px-8 lg:px-12 lg:py-16"><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-[1fr_.55fr] lg:items-end"><div><p className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.2em] text-[#5c954f]"><Sparkles className="h-4 w-4" /> HRestaurant menyusu</p><h1 className="mt-5 max-w-3xl font-serif text-[clamp(3.5rem,7vw,6.5rem)] leading-[.82] tracking-[-.06em]">Təzə dadlar.<br /><em className="font-normal text-[#5c954f]">Hər gün.</em></h1><p className="mt-6 max-w-xl text-lg leading-7 text-[#5d6b60]">{restaurant.data?.name} üçün seçilmiş yeməkləri kəşf edin. 3D baxış olan məhsulları fırladın, yaxınlaşdırın və tərkibini araşdırın.</p></div><div className="rounded-[2rem] border border-[#3e714a]/10 bg-[#e5f0e1] p-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#4c7d4e]">Rəqəmsal təqdimat</p><p className="mt-3 font-serif text-3xl leading-none">Seç, bax, dadını təsəvvür et.</p><Link to={`/restaurants/${restaurantSlug}/reservation`} className="mt-6 inline-flex items-center gap-2 rounded-full bg-[#173d2b] px-5 py-3 text-sm font-bold text-white">Masa rezerv et <ArrowRight className="h-4 w-4" /></Link></div></div><div className="mt-12 grid gap-3 rounded-[1.7rem] border border-[#315d3b]/10 bg-white/70 p-3 shadow-sm backdrop-blur lg:grid-cols-[1fr_auto_auto]"><label className="relative"><span className="sr-only">Yemək axtar</span><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-[#5c6f5d]" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Yemək və ya inqrediyent axtar..." className="h-12 w-full rounded-xl border border-[#315d3b]/15 bg-[#fbfcf9] pl-11 pr-4 outline-none transition focus:border-[#5c954f]" /></label><select aria-label="Kateqoriya" value={categoryId} onChange={(event) => setCategoryId(event.target.value)} className="h-12 rounded-xl border border-[#315d3b]/15 bg-[#fbfcf9] px-4 text-sm font-semibold outline-none"><option value="">Bütün kateqoriyalar</option>{(menu.data ?? []).map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select><label className="flex h-12 items-center gap-2 rounded-xl px-3 text-sm font-semibold text-[#425a49]"><input type="checkbox" checked={popular} onChange={(event) => setPopular(event.target.checked)} className="accent-[#5c954f]" /> Populyar</label></div>{items.length === 0 ? <div className="mt-10 rounded-[2rem] border border-dashed border-[#315d3b]/20 bg-[#f3f8f0] p-14 text-center"><UtensilsCrossed className="mx-auto h-9 w-9 text-[#5c954f]" /><h2 className="mt-4 font-serif text-3xl">Uyğun məhsul tapılmadı</h2><p className="mt-2 text-[#5d6b60]">Axtarışı və ya kateqoriya seçimini dəyişin.</p></div> : <MenuVideoGrid items={items} restaurantSlug={restaurantSlug} />}</div></section>;
}
