import { useQuery } from "@tanstack/react-query";
import { ArrowRight, MapPin, RefreshCw, Store } from "lucide-react";
import { Link } from "react-router-dom";
import { getPublicApiError, getPublicRestaurants } from "@/api/public-api";

export function PublicHomePage() {
  const query = useQuery({ queryKey: ["public-restaurants"], queryFn: getPublicRestaurants });
  if (query.isLoading) return <div className="mx-auto min-h-[65vh] max-w-7xl animate-pulse px-4 py-20"><div className="h-16 max-w-xl rounded-2xl bg-black/10" /><div className="mt-10 grid gap-6 md:grid-cols-2"><div className="h-80 rounded-3xl bg-black/10" /><div className="h-80 rounded-3xl bg-black/10" /></div></div>;
  if (query.isError) return <div className="grid min-h-[65vh] place-items-center px-4 text-center"><div><RefreshCw className="mx-auto h-9 w-9 text-[#b5422d]" /><h1 className="mt-4 font-serif text-4xl">Restoranlar yüklənmədi</h1><p className="mt-3 text-[#70655c]">{getPublicApiError(query.error).message}</p><button type="button" onClick={() => query.refetch()} className="mt-5 rounded-full bg-[#b5422d] px-5 py-3 font-bold text-white">Yenidən cəhd et</button></div></div>;
  return <>
    <section className="bg-[#211d18] px-4 py-20 text-white sm:py-28"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[0.3em] text-[#e8a36c]">HRestaurant şəbəkəsi</p><h1 className="mt-5 max-w-3xl font-serif text-5xl leading-tight sm:text-7xl">Dadınızı seçin, masanızı onlayn rezerv edin.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/65">Aktiv restoranları, menyunu və canlı masa uyğunluğunu bir yerdə kəşf edin.</p></div></section>
    <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><h2 className="font-serif text-4xl">Restoranlarımız</h2>{!query.data?.length ? <div className="mt-8 rounded-3xl border bg-white p-10 text-center"><Store className="mx-auto h-8 w-8 text-[#9a8f85]" /><p className="mt-3">Hazırda public restoran yoxdur.</p></div> : <div className="mt-8 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{query.data.map((restaurant) => <article key={restaurant.id} className="overflow-hidden rounded-[30px] border border-[#ddd4ca] bg-white shadow-sm"><div className="h-52 bg-[#ded5ca]">{restaurant.coverImageUrl ? <img src={restaurant.coverImageUrl} alt={`${restaurant.name} interyeri`} className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center"><Store className="h-9 w-9 text-[#877a70]" /></div>}</div><div className="p-6"><div className="flex items-center justify-between gap-3"><h3 className="font-serif text-3xl">{restaurant.name}</h3><span className={`rounded-full px-3 py-1 text-xs font-bold ${restaurant.isOpenNow ? "bg-green-100 text-green-800" : "bg-stone-100 text-stone-700"}`}>{restaurant.isOpenNow ? "Açıqdır" : "Bağlıdır"}</span></div><p className="mt-3 line-clamp-2 min-h-12 text-sm leading-6 text-[#746960]">{restaurant.description ?? "Menyu və uyğun masalarla tanış olun."}</p><p className="mt-4 flex items-center gap-2 text-sm"><MapPin className="h-4 w-4 text-[#b5422d]" />{restaurant.address}</p><Link to={`/restaurants/${restaurant.slug}`} className="mt-6 inline-flex items-center gap-2 rounded-full bg-[#b5422d] px-5 py-3 font-bold text-white">Restoranı aç <ArrowRight className="h-4 w-4" /></Link></div></article>)}</div>}</section>
  </>;
}
